### ISSUE TITLE
Example code in README does not work 

### ISSUE THREAD

**Issue by daveclay** [graphql-editor/graphql-editor#343]
## PassedSchema not exported?
First error I get after installing:

```
Uncaught TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator)) bundle.js:41
    at App (bundle.js:41:35)
    at renderWithHooks (bundle.js:49146:22)
    at mountIndeterminateComponent (bundle.js:51908:17)
    at beginWork (bundle.js:53107:20)
    at HTMLUnknownElement.callCallback (bundle.js:38096:18)
    at Object.invokeGuardedCallbackDev (bundle.js:38145:20)
    at invokeGuardedCallback (bundle.js:38205:35)
    at beginWork$1 (bundle.js:57947:11)
    at performUnitOfWork (bundle.js:56783:16)
    at workLoopSync (bundle.js:56720:9)

The above error occurred in the <App> component: bundle.js:54131
    at App (http://localhost:3000/static/js/bundle.js:41:35)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

It looks like the issue is on the line:
```
  const [mySchema, setMySchema] = useState<PassedSchema>({
``
and inspecting `PassedSchema` it looks like `graphql-editor` doesn't export it:
```
import { GraphQLEditor, PassedSchema } from 'graphql-editor';
```

The fix appears to be simply removing `PassedSchema` from the import and from `useState`.

# Semicolon in Pizza Schema
The second error:
```
GraphQLError: Syntax Error: Cannot parse the unexpected character ";". bundle.js:17940 
    at syntaxError (bundle.js:72833:10)
    at readToken (bundle.js:76316:78)
    at Lexer.lookahead (bundle.js:76034:108)
    at Lexer.advance (bundle.js:76017:35)
    at Parser.expectToken (bundle.js:78101:19)
    at Parser.parseName (bundle.js:76791:22)
    at Parser.parseNamedType (bundle.js:77367:18)
    at Parser.parseTypeReference (bundle.js:77345:19)
    at Parser.parseFieldDefinition (bundle.js:77575:21)
    at Parser.optionalMany (bundle.js:78196:28)

Uncaught Error: Cannot parse the schema bundle.js:17945 
    at Function.__webpack_modules__../node_modules/graphql-js-tree/lib/Parser/index.js.Parser.parse (bundle.js:17945:11)
    at bundle.js:14310:47
    at invokePassiveEffectCreate (bundle.js:57487:24)
    at HTMLUnknownElement.callCallback (bundle.js:38103:18)
    at Object.invokeGuardedCallbackDev (bundle.js:38152:20)
    at invokeGuardedCallback (bundle.js:38212:35)
    at flushPassiveEffectsImpl (bundle.js:57569:13)
    at unstable_runWithPriority (bundle.js:65317:16)
    at runWithPriority$1 (bundle.js:45509:14)
    at flushPassiveEffects (bundle.js:57446:18)

The above error occurred in the <Editor> component: bundle.js:54138 
    at Editor (http://localhost:3000/static/js/bundle.js:14177:5)
    at Provider (http://localhost:3000/static/js/bundle.js:108494:31)
    at Provider (http://localhost:3000/static/js/bundle.js:108494:31)
    at Provider (http://localhost:3000/static/js/bundle.js:108494:31)
    at Provider (http://localhost:3000/static/js/bundle.js:108494:31)
    at Provider (http://localhost:3000/static/js/bundle.js:108494:31)
    at GraphQLEditor
    at div
    at App (http://localhost:3000/static/js/bundle.js:45:82)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

That just appears to be the parser not liking the `;` in the Pizza schema
```
type Pizza{
  name:String;
}
```
and removing it seems to make it happy again:
```
type Pizza{
  name:String
}
```

My package.json:
```
{
  "name": "graphql-editor-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@monaco-editor/react": "^4.4.1",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "graphql-editor": "^5.2.1",
    "monaco-editor": "^0.33.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.0",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "css-loader": "^6.7.1",
    "file-loader": "^6.2.0",
    "webpack": "^5.71.0",
    "worker-loader": "^3.0.8"
  }
}
```

**Comment by KenEucker** [comment]
I had this same error and the fixes you outline above work to resolve it and the editor renders. I still have further issues from here, _see _, but I wanted to add a comment here to say that I had the same issue. 

Also, of note, I am using Vite and none of the dev dependencies outlined in the example and in your package.json.
